server:
  port: 9502
  servlet.context-path: /email-rest-service/api-v1

#gmail
spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: alexmnv02@gmail.com
    password: 1234567
#    username: email_service@email.ru
#    password: 1234567
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl:
            enable: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000
        smtps:
          checkserveridentity: true
          ssl:
            trust: "*"

