server:
  port: 9501
  servlet.context-path: /email-rest-service/api-v1

#mail-ru
spring:
  mail:
    host: smtp.mail.ru
    port: 465
    username: email_service@email.ru
    password: 1234567
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl:
            enable: true
          connectiontimeout: 15000
          timeout: 15000
          writetimeout: 15000
        smtps:
          checkserveridentity: true
          ssl:
            trust: "*"

